### ISSUE TITLE
文献推荐导入：导入文献作者分隔符问题

### ISSUE THREAD

**Issue by yzy11235** [MinJieDev/Roadmap-Frontend#198]
bibTex字段作者分隔为` and `
但推荐文献导入作者分隔字段为`,`

<img width="864" alt="作者分隔字段问题" src="https://user-images.githubusercontent.com/43177119/83257247-8ee2ce00-a1e6-11ea-92d9-e6100c65a92c.png">
上图中

- 第一条为推荐文献导入（获取第一作者出现问题）
- 第二条为bibTex导入

建议在推荐文献导入文献库时，将分隔字段统一为` and ` （**注，and前后各有一个空格**）

P.S. 又建议推荐文献导入文献库时，尽可能导入全部后端可接受的文献字段，这样有助于文献完整bib的批量导出~

**Comment by luo-junyu** [comment]
需要添加的字段为：
- URL
- Journal
- Year
以上是否正确?
@yzy11235

**Comment by luo-junyu** [comment]
关于作者姓名的bug已修复。但是对于新的字段，由于我们的 createMTdata 目前只有 (title, author, url, note, journal, ref) 字段，后续需要通过别的方式添加
