### ISSUE TITLE
错误处理模态框封装

### ISSUE THREAD

**Issue by Mistariano** [MinJieDev/Roadmap-Frontend#3]
类似`errModal(component, error)`的形式，可以令component弹出错误格式化后的提示模态框

**Comment by luo-junyu** [comment]
## v0.1 如何弹出错误？
### Method 1 : Error Modal (全页面会话式弹窗)
- import ErrModal from './components/ErrModal';
- include ErrModal to template
    - <ErrModal
        v-bind:ErrModalStatus="ErrModalStatus"
        v-bind:ErrContent="ErrContent"
        v-bind:ErrTitle="ErrTitle"
        @cancelErrModal="cancelErrModal">
      </ErrModal>
    - Init data:
        ErrModalStatus: false,
        ErrContent: '',
        ErrTitle: '',
- Add Method: call pushError() to get error modal
    - pushError() {
        this.ErrContent = 'hhh';
        this.ErrTitle = 'ddd';
        this.ErrModalStatus = true;
      },
    - cancelErrModal() {
        window.console.error('[ERROR]: ', this.ErrTitle, this.ErrContent);
        this.modal1 = false;
        window.console.log('updateModal1');
      },

### Method 2: Error Message (页面正中小框、可关闭)
直接使用以下代码进行错误消息提示
更改content中内容即可。
```JavaScript
this.$Message.error({
              background: true,
              content: 'Error Content',
              duration: 5,
              closable: true,
            });
```

**Comment by luo-junyu** [comment]
## v1.0 如何弹出错误？
引入ErrPush函数
```js
import errPush from './components/ErrPush';
```
```js
errPush(this, errCode : string, useModal: boolean, errTitle : string, errContent : string);
```
